### ISSUE TITLE
Error: "compute_indices_weights_cubic" not implemented for 'Half'.

### ISSUE THREAD

**Issue by Enashka** [S4f3tyMarc/Deforum-Studio-Presets#1]
Hey.

Thanks for that. However I can't get it to run. 

I'm loading all settings for Classic-3D-Motion-3.txt for example, and it throws 
"Error: "compute_indices_weights_cubic" not implemented for 'Half'. Please, check your schedules/ init values."

I'm on Forge on a M1 Mac.

Thanks in advance

**Comment by Enashka** [comment]
Update: This only seems to happens for the "Classic" ones. Let me keep troubleshooting and I ll come back with more details

**Comment by S4f3tyMarc** [comment]
Hi try changing the Depth Algorithm to Midas+Adbins (old).

**Comment by Enashka** [comment]
No success, even with Depth warping completely disabled.

**Comment by Enashka** [comment]
"Adabins" seems to be holding.

**Comment by S4f3tyMarc** [comment]
I made them all on windows, so I've not tested them on Mac.

**Comment by Enashka** [comment]
It works for the non classic ones at least with Midas Old. Thanks!
